### PR TITLE
Run tests using JUnit 5.

### PR DESCRIPTION
**Pull request by mincong-h**
Sorry I didn't successfully manage the conflicts and push the diff on the origin PR https://github.com/vavr-io/vavr-jackson/pull/137, so I'm sending a new one.

### CODE REVIEW

**Comment by ruslansennov** [comment]
@nstdio this PR makes changes on your behalf, could you take a look please?

**Comment by mincong-h** [comment]
Yes, please take a look. Compared to the original one, I did the following changes:

- Resolve the conflicts
- Upgrade to latest version of JUnit 5
- Remove some duplicated import statements (some are declared twice in the original PR)
- Move more test files to JUnit5, those recently introduced in master branch

That's pretty much it.

**Comment by nstdio** [comment]
@mincong-h @ruslansennov Thank you.

**Comment by nstdio** [comment]
Should I close the #137 ?

**Comment by mincong-h** [comment]
@nstdio Yes, please. If you feel ok about this one, I will merge it into master.

**Comment by nstdio** [comment]
Sure, feel free to do so.

**Comment by mincong-h** [comment]
Thanks, @nstdio !

**Pull request merged**
