### PR TITLE
Run tests using JUnit 5.

### PR DESCRIPTION
**Pull request by nstdio**

### CODE REVIEW

**Comment by mincong-h** [comment]
@danieldietrich @ruslansennov should we upgrade to JUnit 5? I see Vavr Core is using JUnit 4 and therefore keeping Vavr Jackson aligned with Vavr Core is consistent. However, I think it's better to upgrade to JUnit 5 since @nstdio already did the hard work. And maybe upgrade Vavr Core to JUnit 5 after this one, too. WDYT?

**Comment by ruslansennov** [comment]
@mincong-h I believe that every vavr-project can be moved to JUnit5 independently

**Comment by danieldietrich** [comment]
Yes, I agree. We can do it independently. I already moved to JUnit 5 on the Vavr core 2.0.0 branch. I removed the AssertJ dependency there and used the JUnit 5 assertions instead. The less dependencies, the better. However, rewriting tests is a huge amount of work. You may still use AssertJ...

**Comment by nstdio** [comment]
Closed in favor of #146 .

**Pull request closed without merging**
